# -*- coding: utf-8 -*-
"""Lab2REP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvlU49cT1bO43G1TnWE0Ex5ev22CLKvl

# DICTIONARY IN PYTHON
"""

# creating Dictionary

Students = { 'Ali': 10, 'Hamza': 20,' farrukh': 30,' Haider': 40}

# print keys and values
print('Keys: ',Students.keys())
print('Values: ',Students.values())

# Update value
Students['Hamza '] = 50
print('Updated Dictionary: ',Students)


# Delete a key-value pair
del Students['Ali']
print('After Deletion: ',Students)

"""# SET"""

# create sets

set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

# union, intersection and differences

print('Union: ', set_a | set_b)
print('Intersection: ', set_a & set_b)
print('Difference: ', set_a - set_b)


# Add and remove

set_a.add(6)
set_a.add(7)
set_a.remove(3)
print('updated Set A: ', set_a)

"""# TUPPLE"""

#  creating Tupple

fruits = ('apple', 'banana', 'cherry')
print(fruits)
print('first element: ',fruits[1])
print('Third element: ',fruits[2])

# tupple are immutable so modfication will gives error
# Convert tupple to list

fruits_list = list(fruits)
fruits_list[2] = 'orange'
print('Modified Tupple: ',fruits_list)

"""# LAB2 REP"""

# creating practicing Lab
Nums = [10,20,30,40,50,51,52,53,54,55,56,57,58,59,60]
print('Original Lists: ', Nums)

# Sum, max, and min
print('Sum of List: ', sum(Nums))
print('Max of List: ', max(Nums))
print('Min of List: ', min(Nums))

# Add and remove element
Nums.append(10)
Nums.append(20)
Nums.append(30)
Nums.remove(40)
Nums.remove(50)
Nums.remove(51)
print('New List: ', Nums)

# sort in ascending and descending order
Nums.sort()
print('Ascending Order: ', Nums)
Nums.sort(reverse=True)
print('Descending Order: ', Nums)